import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {lora, raleway} from "@ui/fonts";
import {Providers} from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${raleway.variable} ${lora.variable}`}
      suppressHydrationWarning
    >
      <body className="font-raleway text-base relative text-balance">
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
